### ISSUE TITLE
module_name is always appveyor

### ISSUE THREAD

**Issue by llazzaro** [pydanny/cookiecutter-pymodule#1]
I always used cookiecutter-pymodule to generate new pytohn modules.
However with the current version inside the python module a folder "appveyor" is always created, it ignores the module_name used in the configuration.

this are my steps

```
cookiecutter https://github.com/pydanny/cookiecutter-pymodule.git
```

```
module_name (default is "The name of the to-be-packaged model.")? prueba
....
```

Result of "ls" in the new directory

```
 $ ls
appveyor     CONTRIBUTING.rst  LICENSE      prueba.py   requirements-dev.txt  setup.cfg  test_prueba.py
AUTHORS.rst  HISTORY.rst       MANIFEST.in  README.rst  requirements.txt      setup.py   tox.ini

```

a directory appveyor is always created.

Sorry if I missed something!

**Comment by mgaitan** [comment]
@llazzaro [appveyor](http://www.appveyor.com/) is a CI service, analog to Travis. the cutter create the `prueba.py` module for you

**Comment by llazzaro** [comment]
I see your point in previous version a folder "prueba" was created.
I wasn't expecting to be force to use appveyor and tought that it was a bug.

thanks for answer

**Comment by pydanny** [comment]
Oops. Sorry I somehow missed this issue. Anyway, opened #3
